### ISSUE TITLE
Keycloak BuildException: "this version of the Java Runtime only recognizes class file versions up to 61.0"

### ISSUE THREAD

**Issue by chefmoensch** [canchanchara/keycloak-churchtools-storage-provider#18]
Hallo zusammen,

Ich bin gerade auf euer sehr geniales Projekt gestossen und wollte das bei mir austesten. Ich habe das docker-compose.yml verwendet, welches ihr in eurem Repo verwendet und dieses startet die Services auch so wie gewollt. Jedoch startet der Container Keycloak nicht, weil er mit der folgenden Fehlermeldung fehlschlägt

ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
       [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.UnsupportedClassVersionError: de/canchanchara/keycloak/storage/ChurchToolsUserStorageProviderFactory has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
       at java.base/java.lang.ClassLoader.defineClass1(Native Method)
       at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
       at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:508)
       at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
       at java.base/java.lang.Class.forName0(Native Method)
       at java.base/java.lang.Class.forName(Class.java:467)
       at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
       at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
       at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
       at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
       at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
       at org.keycloak.provider.DefaultProviderLoader.load(DefaultProviderLoader.java:60)
       at org.keycloak.provider.ProviderManager.load(ProviderManager.java:93)
       at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:690)
       at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:398)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
       at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
       at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
       at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
       at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
       at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
       at java.base/java.lang.Thread.run(Thread.java:840)
       at org.jboss.threads.JBossThread.run(JBossThread.java:501)

Ich vermute, dass das einfach die Java Version (21) ist, welche offensichtlich noch nicht im Keycloak Image verwendet wird. Aus diesem Grund habe ich einfach mal beim pom.xml bei mir lokal die Version auf 17 gesetzt und geschaut, obs dann funktioniert.

Ich denke ich lasse das Feedback so für euch einfach mal hier, falls ihr euch darum kümmern möchtet. Evtl. seid ihr ja auch offen für fixes/pull requests (ich weiss ja nicht wie wichtig die Java Version 21 für euch ist)?

Freundliche Grüsse
Jonas Wagner (Zollhaus Luzern, https://zollhaus.ch)

Edit: Mit Java Version 17 startet keycloak bei mir.

**Comment by canchanchara** [comment]
Ich  habe die compose datei aktualisiert, da war noch eine alte Version drin.
Mit Keyloak 26.0.5 wird java 21 genutzt.

**Comment by chefmoensch** [comment]
Danke vielmals :)
