### ISSUE TITLE
UserQueryProvider implementieren

### ISSUE THREAD

**Issue by daniel-lerch** [canchanchara/keycloak-churchtools-storage-provider#4]
Wenn ein Storage Provider in Keycloak die Schnittstelle `UserQueryProvider` implementiert, kann man als Admin in der Liste der Nutzer suchen. Im produktiven Einsatz weiß ich nicht, warum man das tun sollte, weil eine Suche in ChurchTools sehr viel praktischer ist, aber zum Testen, wäre es sehr praktisch, weil man auf einen Blick sieht, ob die ChurchTools Anbindung funktioniert. Auch fehlerhaft gesetzte Berechtigungen des Accounts in `ServerCredentials` ließen sich so einfacher debuggen.

**Comment by canchanchara** [comment]
Hat mich auch parallel heute morgen beschäftigt.
Eine rudimentäre Suche nach Benutzernamen sollte gehen.
Gerne testen in 0.0.2-alpha.

**Comment by daniel-lerch** [comment]
Die Suche funktioniert und liefert Ergebnisse. Mit `' '` (Leerzeichen) ist es außerdem möglich, nach allen Nutzern zu suchen, was mir gefällt.

Die aktuelle Implementation enthält glaube ich aber noch zwei Bugs:
1. Pagination funktioniert nicht korrekt. Es werden weniger Ergebnisse angezeigt als unten eingestellt.
2. Wenn man nach `'*'` (Stern) sucht, wird eine Fehlermeldung angezeigt:
_No users found, could be due to wrongly configured federated provider Unexpected non-whitespace character after JSON at position 2 (line 1 column 3)_

**Comment by canchanchara** [comment]
Probiers nochmal neu aus mit 0.0.3-alpha

**Comment by daniel-lerch** [comment]
Suche nach `'*'` (Stern) funktioniert jetzt und es wird auch die korrekte Zahl an Ergebnissen angezeigt. Wenn ich jedoch auf die zweite Seite gehe, fliegt eine Exception, die sogar das Keycloak Frontend crasht. Dieser Fehler tritt unabhängig davon auf, wie viele Elemente man auf der ersten Seite anzeigen lässt.

Hier der relevante Teil des Stacktrace:
```
2023-10-04 20:38:57,256 INFO  [org.keycloak.quickstart.storage.user.ChurchToolsApi] (executor-thread-22) findPersons searchterm: firstResult: null maxResults: null
2023-10-04 20:38:57,908 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-22) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "firstResult" is null
        at org.keycloak.quickstart.storage.user.ChurchToolsApi.findPersons(ChurchToolsApi.java:192)
        at org.keycloak.quickstart.storage.user.ChurchToolsUserStorageProvider.searchForUserStream(ChurchToolsUserStorageProvider.java:79)
        at org.keycloak.quickstart.storage.user.ChurchToolsUserStorageProvider.searchForUserStream(ChurchToolsUserStorageProvider.java:105)
        at org.keycloak.storage.user.UserQueryMethodsProvider.searchForUserStream(UserQueryMethodsProvider.java:104)
        at org.keycloak.storage.user.UserCountMethodsProvider.getUsersCount(UserCountMethodsProvider.java:111)
        at org.keycloak.storage.UserStorageManager.lambda$searchForUserStream$26(UserStorageManager.java:481)
        at org.keycloak.storage.UserStorageManager.lambda$query$6(UserStorageManager.java:251)
```

**Comment by canchanchara** [comment]
probiers mal mit 0.0.4-alpha

**Comment by daniel-lerch** [comment]
Ich habe jetzt direkt die 0.0.5-alpha installiert und da klappt es jetzt einwandfrei.
